import React from 'react';
import Icon from '../components/Icon';
import { Badge } from '../components/Card';

const PLANS = {
  en: [
    {
      id: 'free',
      name: 'Free',
      subtitle: 'The Essential',
      price: 'R$ 0',
      period: 'forever',
      ideal: 'Students and early-career devs who need a professional CV fast.',
      features: [
        '1 active profile',
        'Default template (André Elias Style)',
        'Unlimited generations for your own profile',
        'Small "Generated by MatchCV" watermark in footer',
      ],
      cta: 'Get started free',
      highlight: false,
    },
    {
      id: 'pro',
      name: 'Pro',
      subtitle: 'The Active Candidate',
      price: 'R$ 19,90',
      period: '/month',
      annual: 'R$ 149 billed annually',
      ideal: 'Devs applying to multiple jobs who need CV variations.',
      features: [
        'Up to 5 resume versions (e.g. Java-focused, React-focused)',
        'Full LaTeX template library (Modern, Classic, Minimalist)',
        '.tex source download for manual editing in Overleaf',
        'Clean PDF — no watermarks',
        'Priority compilation queue',
      ],
      cta: 'Start Pro',
      highlight: true,
      badge: 'Most popular',
    },
    {
      id: 'lifetime',
      name: 'Lifetime',
      subtitle: 'The Senior Engineer',
      price: 'R$ 97',
      period: 'one-time',
      ideal: 'Want a career backup tool for life.',
      features: [
        'Everything in Pro, forever',
        'All future templates included',
        'Lifetime updates at no extra cost',
        'Priority support',
      ],
      cta: 'Buy lifetime access',
      highlight: false,
    },
  ],
  pt: [
    {
      id: 'free',
      name: 'Free',
      subtitle: 'O Essencial',
      price: 'R$ 0',
      period: 'para sempre',
      ideal: 'Estudantes e devs em início de carreira que precisam de um CV profissional rápido.',
      features: [
        '1 perfil ativo',
        'Template padrão (André Elias Style)',
        'Gerações ilimitadas para seu próprio perfil',
        'Pequena menção "Generated by MatchCV" no rodapé',
      ],
      cta: 'Começar grátis',
      highlight: false,
    },
    {
      id: 'pro',
      name: 'Pro',
      subtitle: 'O Candidato Ativo',
      price: 'R$ 19,90',
      period: '/mês',
      annual: 'R$ 149 cobrado anualmente',
      ideal: 'Devs aplicando para múltiplas vagas que precisam de variações do currículo.',
      features: [
        'Até 5 versões de currículo (ex: focado em Java, outro em React)',
        'Biblioteca completa de templates LaTeX (Modern, Classic, Minimalist)',
        'Download do código-fonte .tex para edição no Overleaf',
        'PDF limpo e profissional — sem marcas d\'água',
        'Prioridade na fila de compilação',
      ],
      cta: 'Assinar Pro',
      highlight: true,
      badge: 'Mais popular',
    },
    {
      id: 'lifetime',
      name: 'Lifetime',
      subtitle: 'O Engenheiro Sênior',
      price: 'R$ 97',
      period: 'pagamento único',
      ideal: 'Quem quer ter uma ferramenta de backup de carreira para a vida toda.',
      features: [
        'Tudo do plano Pro para sempre',
        'Acesso a todos os novos templates adicionados futuramente',
        'Atualizações vitalícias sem custo extra',
        'Suporte prioritário',
      ],
      cta: 'Comprar acesso vitalício',
      highlight: false,
    },
  ],
};

export default function PlansScreen({ lang, t, onSelect, onBack }) {
  const plans = PLANS[lang];

  return (
    <div style={{
      minHeight: '100vh', background: 'var(--bg)',
      backgroundImage: 'radial-gradient(ellipse at 50% 0%, var(--accent-soft) 0%, transparent 50%)',
      padding: '64px 40px',
      display: 'flex', flexDirection: 'column', alignItems: 'center',
    }}>
      <div style={{ maxWidth: 1040, width: '100%' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: 56 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 32 }}>
            <div style={{
              width: 30, height: 30, borderRadius: 8, background: 'var(--ink)', color: 'var(--bg)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontWeight: 700, fontSize: 15,
            }}>M</div>
            <span style={{ fontWeight: 650, fontSize: 16, letterSpacing: '-0.01em' }}>{t.appName}</span>
          </div>
          <h1 style={{ fontSize: 42, fontWeight: 600, letterSpacing: '-0.03em', margin: '0 0 14px', lineHeight: 1.1 }}>
            {lang === 'pt' ? 'Escolha seu plano' : 'Choose your plan'}
          </h1>
          <p style={{ fontSize: 16, color: 'var(--ink-3)', margin: 0, lineHeight: 1.6 }}>
            {lang === 'pt'
              ? 'Comece grátis. Faça upgrade quando precisar de mais.'
              : 'Start free. Upgrade when you need more.'}
          </p>
        </div>

        {/* Plans grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20, alignItems: 'start' }}>
          {plans.map((plan) => (
            <div key={plan.id} style={{
              background: plan.highlight ? 'var(--ink)' : 'var(--surface)',
              color: plan.highlight ? 'var(--bg)' : 'var(--ink)',
              borderRadius: 20,
              padding: 28,
              boxShadow: plan.highlight ? 'var(--shadow-lg)' : 'var(--shadow-sm)',
              position: 'relative',
              display: 'flex', flexDirection: 'column', gap: 0,
            }}>
              {plan.badge && (
                <div style={{ position: 'absolute', top: -12, left: '50%', transform: 'translateX(-50%)' }}>
                  <Badge tone="accent" style={{ background: 'var(--accent)', color: 'var(--accent-ink)', boxShadow: 'none' }}>
                    <Icon name="star" size={11} stroke={2.5} />{plan.badge}
                  </Badge>
                </div>
              )}

              <div style={{ marginBottom: 20 }}>
                <div style={{ fontSize: 12, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', opacity: 0.6, marginBottom: 4 }}>
                  {plan.subtitle}
                </div>
                <div style={{ fontSize: 22, fontWeight: 650, letterSpacing: '-0.01em' }}>{plan.name}</div>
              </div>

              <div style={{ marginBottom: 24 }}>
                <span style={{ fontSize: 38, fontWeight: 700, letterSpacing: '-0.03em' }}>{plan.price}</span>
                <span style={{ fontSize: 14, opacity: 0.6, marginLeft: 4 }}>{plan.period}</span>
                {plan.annual && (
                  <div style={{ fontSize: 12, opacity: 0.55, marginTop: 4 }}>{plan.annual}</div>
                )}
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 28, flex: 1 }}>
                {plan.features.map((f, i) => (
                  <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                    <div style={{
                      width: 18, height: 18, borderRadius: 999, flexShrink: 0, marginTop: 1,
                      background: plan.highlight ? 'rgba(255,255,255,0.15)' : 'var(--success-soft)',
                      color: plan.highlight ? 'var(--bg)' : 'var(--success)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                    }}>
                      <Icon name="check" size={11} stroke={3} />
                    </div>
                    <span style={{ fontSize: 13.5, lineHeight: 1.45, opacity: plan.highlight ? 0.9 : 1 }}>{f}</span>
                  </div>
                ))}
              </div>

              <div style={{ fontSize: 12, opacity: 0.5, marginBottom: 16, lineHeight: 1.45 }}>
                <Icon name="user" size={12} style={{ marginRight: 5, verticalAlign: '-2px' }} />
                {lang === 'pt' ? 'Ideal para: ' : 'Ideal for: '}{plan.ideal}
              </div>

              <button
                onClick={() => onSelect(plan.id)}
                style={{
                  width: '100%', height: 44, borderRadius: 10, fontWeight: 600, fontSize: 14,
                  cursor: 'pointer', fontFamily: 'inherit', border: 'none',
                  background: plan.highlight ? 'var(--bg)' : 'var(--ink)',
                  color: plan.highlight ? 'var(--ink)' : 'var(--bg)',
                  transition: 'opacity 120ms, transform 120ms',
                }}
                onMouseDown={e => { e.currentTarget.style.transform = 'scale(0.98)'; }}
                onMouseUp={e => { e.currentTarget.style.transform = ''; }}
                onMouseLeave={e => { e.currentTarget.style.transform = ''; }}
              >
                {plan.cta}
              </button>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{ textAlign: 'center', marginTop: 48, display: 'flex', flexDirection: 'column', gap: 16, alignItems: 'center' }}>
          <div style={{ display: 'flex', gap: 28, fontSize: 13, color: 'var(--ink-3)' }}>
            {[
              { icon: 'check', text: lang === 'pt' ? 'Cancele a qualquer momento' : 'Cancel anytime' },
              { icon: 'check', text: lang === 'pt' ? 'Sem cobrança automática no Free' : 'No auto-charge on Free' },
              { icon: 'check', text: lang === 'pt' ? 'Suporte por e-mail' : 'Email support' },
            ].map((item, i) => (
              <span key={i} style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                <Icon name={item.icon} size={13} stroke={2.5} style={{ color: 'var(--success)' }} />
                {item.text}
              </span>
            ))}
          </div>
          <button onClick={onBack} style={{
            fontSize: 13, color: 'var(--ink-3)', display: 'inline-flex', alignItems: 'center', gap: 6,
            cursor: 'pointer', fontFamily: 'inherit', background: 'none', border: 'none',
          }}>
            <Icon name="arrowLeft" size={13} />
            {lang === 'pt' ? 'Voltar para o login' : 'Back to sign in'}
          </button>
        </div>
      </div>
    </div>
  );
}
